eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 10002
spring:
    application:
        name: search-service
    data:
        elasticsearch:
            repositories:
                enabled: true
    elasticsearch:
        rest:
            uris: http://localhost:9200