eureka:
    instance:
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8804
spring:
    application:
        name: search-service
    data:
        elasticsearch:
            repositories:
                enabled: true
    elasticsearch:
        rest:
            uris: http://192.168.0.6:9200