eureka:
    instance:
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8085
spring:
    application:
        name: cjd-cart
    mvc: 
        view: 
              suffix: .jsp
ftpclient:
    basepath: E:/files/
    filepath: /
    host: 192.168.0.11
    password: 1
    username: Administrator
    port: 21