eureka:
    instance:
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8085
spring:
    application:
        name: cjd-cart
    mvc: 
        view: 
              suffix: .jsp
ftpclient:
    basepath: G:/nginx-1.17.5/html/docs/
    filepath: /
    host: 192.168.1.103
    password: 13579
    username: Administrator
    port: 21