server:
    port: 8761
eureka:
    instance:
        hostname: localhost
        prefer-ip-address: true
    client:
        fetchRegistry: false
        registerWithEureka: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/