eureka:
    instance:
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 10002
spring:
    application:
        name: rabbitmq-service
    rabbitmq:
        host: localhost
        password: 123456
        port: 5672
        username: jwang