eureka:
    instance:
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8084
spring:
    application:
        name: cjd-passport
    mvc: 
        view: 
              suffix: .jsp