eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8190
spring:
    application:
        name: cjd-portal
    mvc: 
        view: 
              suffix: .jsp