eureka:
    instance:
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 10001
spring:
    application:
        name: redis-service
    redis:
        hostName: 127.0.0.1
        port: 6379