eureka:
    instance:
        hostname: 10.2.100.84
    client:
        serviceUrl:
            defaultZone: http://10.2.8.132:8761/eureka/,http://10.2.8.132:8762/eureka/
server:
    port: 10001
spring:
    application:
        name: redis-service
    redis:
        hostName: 10.2.8.132
        port: 6379